//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace marshrutkaby
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drivers
    {
        public int IdDriver { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Birthday { get; set; }
        public string License { get; set; }
        public string NumberPhone { get; set; }
        public string Password { get; set; }
        public string Rating { get; set; }
        public int TransportCompanyIdTransportCompany1 { get; set; }
    
        public virtual TransportCompany TransportCompany { get; set; }
    }
}
