//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace marshrutkaby
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MarshrutkabyDBModelContainer : DbContext
    {
        public MarshrutkabyDBModelContainer()
            : base("name=MarshrutkabyDBModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Registration> RegistrationSet { get; set; }
        public virtual DbSet<Cars> CarsSet { get; set; }
        public virtual DbSet<Drivers> DriversSet { get; set; }
        public virtual DbSet<TransportCompany> TransportCompanySet { get; set; }
        public virtual DbSet<Order> OrderSet { get; set; }
    }
}
