//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace marshrutkaby
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int IdOrder { get; set; }
        public int IdPassenger { get; set; }
        public int IdTransportCompanyIdTransportCompany { get; set; }
    
        public virtual Registration Registration { get; set; }
        public virtual TransportCompany TransportCompany { get; set; }
    }
}
